apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tracing-demo
    service: shopping
    shard: blue
  name: shopping-blue
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-demo
      service: shopping
      shard: blue
  template:
    metadata:
      labels:
        app: tracing-demo
        service: shopping
        shard: blue
    spec:
      containers:
      - name: shopping
        image: 192.168.1.8/3dtracing/shopping:latest
        imagePullPolicy: Always
        # command:
        # - "java"
        # - "-jar"
        # - "/shopping.jar"
        ports:
        - containerPort: 4444
          name: application
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shopping
  namespace: default
spec: 
  selector:
    app: tracing-demo
    service: shopping  
  type: LoadBalancer
  ports:
  - name: application
    port: 4444
